# Generated by Django 3.1.1 on 2020-09-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200913_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productimage',
            field=models.ImageField(blank=True, default='/images/product.jpg', null=True, upload_to='images/'),
        ),
    ]
