# Generated by Django 3.0.3 on 2020-09-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_extrainfo_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='user',
            new_name='User',
        ),
    ]
