# Generated by Django 3.0.3 on 2020-09-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200902_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='User',
            new_name='user',
        ),
    ]
