# Generated by Django 3.0.3 on 2020-09-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200902_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='Nationality',
            field=models.IntegerField(choices=[(4, 'Afghanistan'), (8, 'Albania'), (12, 'Algeria'), (24, 'Angola'), (10, 'Antarctica'), (32, 'Argentina'), (36, 'Australia'), (40, 'Austria'), (31, 'Azerbaijan'), (44, 'Bahamas'), (48, 'Bahrain'), (50, 'Bangladesh'), (56, 'Belguim'), (70, 'Bosnia and Herzegovina'), (76, 'Brazil'), (100, 'Bulgaria'), (854, 'Burkina Fasu'), (108, 'Burundi'), (116, 'Cambodia'), (120, 'Cameroon'), (124, 'Canada'), (140, 'Central African Republic'), (148, 'Chad'), (152, 'Chile'), (156, 'China'), (170, 'Colombia'), (180, 'the Democratic Republic of Congo'), (188, 'Costa Rica'), (384, "Côte d'Ivoire"), (191, 'Croatia'), (192, 'Cuba'), (196, 'Cyprus'), (203, 'Czech Republic'), (208, 'Denmark'), (262, 'Djibouti'), (214, 'Dominican Republic'), (218, 'Ecuador'), (818, 'Egypt'), (222, 'El Salvador'), (226, 'Equatorial Guinea'), (232, 'Eritrea'), (233, 'Estonia'), (231, 'Ethiopia'), (234, 'Faroe Islands'), (246, 'Finland'), (250, 'France'), (266, 'Gabon'), (270, 'Gambia'), (268, 'Georgia'), (276, 'Germany'), (300, 'Greece'), (304, 'Greenland'), (320, 'Guatemala'), (324, 'Guinea'), (624, 'Guinea-Bissau'), (340, 'Honduras'), (344, 'Hong Kong'), (348, 'Hungary'), (352, 'Iceland'), (356, 'India'), (360, 'Indonesia'), (364, 'Islamic Republic of Iran'), (368, 'Iraq'), (372, 'Ireland'), (380, 'Italy'), (388, 'Jamaica'), (392, 'Japan'), (400, 'Jordan'), (398, 'Kazakhstan'), (404, 'Kenya'), (410, 'Republic of Korea'), (414, 'Kuwait'), (428, 'Latvia'), (422, 'Lebanon'), (430, 'Liberia'), (434, 'Libya'), (438, 'Liechtenstein'), (440, 'Lithuania'), (442, 'Luxembourg'), (450, 'Madagascar'), (454, 'Malawi'), (458, 'Malaysia'), (462, 'Maldives'), (466, 'Mali'), (470, 'Malta'), (478, 'Mauritania'), (480, 'Mauritius'), (484, 'Mexico'), (504, 'Morocco'), (508, 'Mozambique'), (524, 'Nepal'), (528, 'Netherlands'), (554, 'New Zealand'), (562, 'Niger'), (566, 'Nigeria'), (578, 'Norway'), (512, 'Oman'), (586, 'Pakistan'), (275, 'Palestine'), (591, 'Panama'), (600, 'Paraguay'), (604, 'Peru'), (608, 'Philippines'), (616, 'Poland'), (620, 'Portugal'), (630, 'Puerto Rico'), (634, 'Qatar'), (642, 'Romania'), (643, 'Russia'), (646, 'Rwanda'), (682, 'Saudi Arabia'), (686, 'Senegal'), (688, 'Serbia'), (702, 'Singapore'), (703, 'Slovakia'), (705, 'Slovenia'), (706, 'Somalia'), (710, 'South Africa'), (728, 'South Sudan'), (724, 'Spain'), (144, 'Sri Lanka'), (729, 'Sudan'), (748, 'Swaziland'), (752, 'Sweden'), (756, 'Switzerland'), (760, 'Syrian Arab Republic'), (158, 'Taiwan'), (762, 'Tajikistan'), (834, 'Tanzania'), (764, 'Thailand'), (768, 'Togo'), (788, 'Tunisia'), (792, 'Turkey'), (800, 'Uganda'), (804, 'Ukraine'), (784, 'United Arab Emirates'), (826, 'United Kingdom'), (840, 'United States of America'), (858, 'Uruguay'), (860, 'Uzbekistan'), (862, 'Venezuela'), (887, 'Yemen'), (894, 'Zambia'), (716, 'Zimbabwe')], default=1),
        ),
    ]
