# Generated by Django 3.0.3 on 2020-09-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200903_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='dayofbirth',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=1),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='monthofbirth',
            field=models.IntegerField(choices=[(1, 'Janueary'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='yearofbirth',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
