# Generated by Django 3.0.3 on 2020-09-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200906_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='productimage',
        ),
    ]
