# Generated by Django 3.0.3 on 2020-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200906_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
