# Generated by Django 3.0.3 on 2020-09-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200906_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
