# Generated by Django 3.0.3 on 2020-09-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_extrainfo_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='profilepicture',
        ),
    ]
