# Generated by Django 3.0.3 on 2020-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_extrainfo_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
