# Generated by Django 3.0.3 on 2020-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_extrainfo_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='profileimage',
            field=models.ImageField(blank=True, default='maleprofile.jpg', null=True, upload_to='images/'),
        ),
    ]
