# Generated by Django 3.0.3 on 2020-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_auto_20200907_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
