# Generated by Django 3.0.3 on 2020-09-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20200907_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productimage',
            field=models.ImageField(blank=True, default='product.jpg', null=True, upload_to='images/'),
        ),
    ]
