# Generated by Django 3.0.3 on 2020-09-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20200908_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profilepic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.extrainfo'),
        ),
    ]
