# Generated by Django 3.0.3 on 2020-09-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_post_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profilepic',
        ),
    ]
