# Generated by Django 3.0.3 on 2020-09-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_remove_post_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profilepic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.extrainfo'),
        ),
    ]
