# Generated by Django 3.0.3 on 2020-09-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_remove_post_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='profileimage',
        ),
    ]
