# Generated by Django 3.0.3 on 2020-09-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_remove_extrainfo_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productimage',
            field=models.ImageField(blank=True, default='/images/product.jpg', null=True, upload_to='media/images/'),
        ),
    ]
